[build]
builder = "NIXPACKS"
buildCommand = "bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate"

[deploy]
startCommand = "bundle exec rails server -p $PORT -e $RAILS_ENV"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
name = "dental-system-prod"
