# Cron jobs for Sidekiq
fetch_emails:
  cron: '*/10 * * * *'  # Every 10 minutes
  class: ImapFetcherJob
  description: "Fetch new emails from IMAP server"

daily_reminders:
  cron: '0 9 * * *'  # Every day at 9 AM
  class: DailyReminderJob
  description: "Send daily appointment reminders"

cleanup_old_logs:
  cron: '0 2 * * 0'  # Every Sunday at 2 AM
  class: CleanupJob
  description: "Clean up old logs and temporary files"