name: Deploy to Railway

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dental_system_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.8
        bundler-cache: true
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        bundle install
        
    - name: Setup Database
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:migrate RAILS_ENV=test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/dental_system_test
        REDIS_URL: redis://localhost:6379/0
        RAILS_ENV: test
        
    - name: Precompile assets
      run: bundle exec rails assets:precompile
      env:
        RAILS_ENV: test
        SECRET_KEY_BASE: test_secret_key_base
        
    - name: Run RSpec tests
      run: bundle exec rspec
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/dental_system_test
        REDIS_URL: redis://localhost:6379/0
        RAILS_ENV: test
        SECRET_KEY_BASE: test_secret_key_base
        
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
      
    - name: Security Audit
      run: |
        gem install bundler-audit
        bundler-audit --update
        bundle exec bundle-audit check

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v1.8.0
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🚀 Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
